---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-build ."
      - "docker tag oschku/mvp-build 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-repo"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-repo"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoibjA2Wlg4cHJNcFp2OXM3TTdpRWR0RTI5cGpEek0wQzFPVVNQRVpwTFdyTzdXRVR4SDRhRVFGeHhhelZqV2tCYy91Ynk5WGx4UFY5bVhuTVh6ZVhxdmpUVmRIeEg5WE4zYmNxQ3hXbWljVVo0UW1kRDVhT3I3VUIvT2tqNnpmNHF4Z0taaDlDbU52TzF6R2tpR3dzY2tOOVZBV0d1eWZQc0Y2R3pUbFoybmh6bHlDWXo0QWtlMnZmVjdGK3hDRWtjNC9GYzJ3bFNvdDhTZGpwc25rZFcreklITDNOQWFwd3VWUlYwUDk3Rlg3eFdpZ2tEK2ZjbDdTQmthQzlmNnBQRXMvOHVDZlhCOXZBL2lzSjlhQStsT21yUW5lYUdwc3RBaWlqa1N0WGwrWlEvdWQzcnVzMHZacUpBODJUSWlMYzJINFp3NHZxS0R6cmUrMk56ZXQ4MGFFYW1pTGZXallyTHFsaGxySjlPWE83MzlIdlljVGhWb29JUWxlcmRmVHJKVTNQeWRlKzgyRHJpU0FqKzQ2eVRyS2M2NENYcVlObmZ6WS9ZWDArWWJweGllaE4raG5icllnaU40UUF5eGZRZ3JSc2dxYVJGMFluNUZyZHNYKzlWcGFyQXlpRXU2aGhPTXAzdC9ZYno0V2daV3NwK0NORXZrR3ovWEVsY1VvL0Q1MXdvR1ByTit5dWh1emlrNmdpOGlHTy9MWDArZWVBUzhQK0dpWElSWUh4NlNmMVZrUWVISDg1ZlJxdFQ1OVY1Uk1GODJ1OGRkZ2VGSWRpc0JJcU1DSWJiR0FOVjI3NWNJSE5MYisyN1B5RXZZMjlIQ2dwYWV3ckpXNnFGQkl5Yitpc2w1YWN6REcramY5Y2VFbHVJalRSWHNlK0YrT3p4dFlnbmR5NDZXcVNPU09UK2c3ekpWNXo0Y29VUTZlOHIzbk9Pd2ZkbTZwL3lVdDJZbUVzcnRyUGFWQU1Od3hYOGkwU3o1YVdpdnNlQ3ZrWk9NYjZkNnA1WG52SFlieWpZQkVDa3RyVjV2SlpZc0docDJ5VGZQMlNiNGduY2g1OG4rblF1c1hpclJaclpjM1BJc0RVTHRPNzRwazRGOUpPOUtkVE9rZnlpbno3dVRRKzhoYWRhci9JQXh4Tm93ajZ0bHhTZGtwaUd2c2xnaFJaU2NTeUYzVnpJc0xDU2tVM1lyb2dRanBLc2RIblF0SDI3aUsrTkhXN3l6U2VwNThzVlo1dE0wN0VnK1pFdStMck15UTZpbER1Q29xMUpCbjcxb0FHR0tDUVI5RzNudTJUOVJOalNpTTZNTG93eTFPTngrbUtRNksvL3l0cDc4M0tPWFJOVnlMa1Jjem13cEd6T0lRT2VWcFRKcTU0V1FkOFdEaDR0aXh4TDh2NkJub1BpeDdVMy81VFU3ZkFuNHJUKzVGWFZ6THVIU0gzTms2bEd2RmlQaG1GaDV4SmNNMTRaVUE9PSIsImRhdGFrZXkiOiJBUUlCQUhoZnJGUTJhSUl3RjVWYzc5UkhFUEduY1VXdXIyL0p6TTh0L1p6b0V0UnJBZ0dlQTBoeDIzdHNkaVZQSVBPQ3VkejFBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU1PMmhuREZyOUYwUm5tSDhKQWdFUWdEdXBLL0dVSUxmTHFNUEdsSkcwT212bzZOSnBMRTUvdVBRU2lGdW5ZTmlKODl3dHA5d05wOTFZTmI0V2NlaWVjMFZVaFNWbzNwYWxMWHNPQnc9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTYxMzU5MTUyM30= 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1

