---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-build ."
      - "docker tag oschku/mvp-build 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-repo"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-repo"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoibzVSTWVnRXQvV3JIQjA0U1NYbldUQkE0NGh2NXNNcGsxV3Z0NXppUzZBWkU0clJQTzZ4Wll1WStsTDdoWG9KcEZxTlRaRU85MWxtaFlEaW5aSWRsTmUzTW5jcTRvZ3FQbGlIcXFUK3MrbHVsa3BuZWhCQ0RieEYvMjdIOThDdWlvQWRmNzVaV0lrdE9WZERPaXpETnBObSs3R0g0Wk1SbVd5bGRwTDFBZzIrM2VaSjJxU0JpMEovZ2lFSXpyRGcza2JVNG5oNWRpWlM2M0tGSEpsbVRhK2J3SXBsUFk4d2FPTnZkakxxaHRteURoMEREZnlOdXVvZmxmSllubDg1Sm1qWDUzU2lCUExrVTNCbm9HWStkRTl0Ylg4cTA2TmxpOE5PQWpDUTlXa2lCNWFuQjkvdWRweEFHWjkrZjhnQ29iSHVQc2JXQ0dvU1l0aStXVGpkNUxueEd6N3d2aTViRkVsNGxYRTlmejVadCtxWHVoYkcreXVjblY5TE9sSS9vZFhWTnIyOGhaa0Y4NnkwbWFEVVlCRWM5SGdOWmZ0dXIvbCt2UG51RU9xS1BnVWhITE9UZTNySys3VExzVVpIMytobjRCZ3A0bDI2Zm5zVSt6K2NZY0dlbm1HQTlzVjV1VHZFSmVCVzBzaXd2cll4ajJFUVk1R1FlZ2k2VS9FejlmVGpkeHkrUytuM3N3NWxOMDJYM1lBbUtXOGEvMUMzbmJjZEFrMXBVNjN1MEhCNWp4amFJazcyWmVwWGRqcW4rNnVMRm9qNXI1ZytZUlFaNEIyZ0pWV0dsNVQrWHk3YmYzdWl4V1hCdXN3ejV6b3BvSy9mR2tUWlo3d3NxL2pDcXZITnZiVDZ5QzZLaUhqRUtpVVVlWFl2eE8wWXRKMXZPd0E2RG0xZ2FhZkNrdWU2VFlUQTVvN2ZMYlRla0I1dVFTa3Z5R2xkRHpmM0o4VW52WGZxOXFLTytiVjc4NWxUR2hFZDZWcXRycnNWT1JSQXhaRmxhOStpMG1NRXBIYkRVblQybGJaRUo5ZzNkbS8wM1dTN0txcEtQanRleFRMcllWZ2x2NVNDL1Y0cHJWWGU5dGROd0FtMHo3TXJDdzNDOFZSSVdQUmZOc2FTTkpVM1IwbmJibTRzd21OY1FRejdQQVM1QlgxR2phUjd3emozVytLTFF3S3Bwajd1cHFYM1hGT1JvR2JLdXhGcWNhRm5DWEFtdDJORmJBc0ZGbklpMFJzVGpwZUZBOWlVSnZaQUhiZ2VYaDFTbmNzZ3pkQUJManhLMU1DZFk5TERJdXlFRnBqZERHQkJUR0xEclV4VGpvMWMxNGlEVmU2RVJlMUhVQjRIdjQ3Q3IycmlOZVZ0WFphVHpuOG9CbVBLNTZsNExDM3Q5WElaWUJoT1o3bDNHNU44WlIvYXNRV0xBMGkyQk8rL3ZkZkRJOUFPTlREY1JrbUdBbndxK3NEdGFQTnBnTlJEbWdvQXNQV3ZBMk5QalpnPT0iLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdFTWVlT0RIb1hxQk11K3hadG1zWTRWQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNMk5tWWhMWkFXZnFSV0dMQUFnRVFnRHRzY2pISjF4RlVNTFlTSVBJWWJnQ1gxQlQ1V2JCS3lPYkcxcGIxeEtBNjVTUVRuTTZOcE1sMFU1aWJjRFViRzlRaGQzVUhRS004WHJqODRnPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MTQwNDc4NDd9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1

