---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-build ."
      - "docker tag oschku/mvp-build axwdigitaldocker/mvp-build:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push axwdigitaldocker/mvp-build:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"axwdigitaldocker\" --password=\"075l2q1O!\""
      - "printf [{'name':'your.task.definition.name','imageUri':'%s'}] $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json"
artifacts:
  files: 
    - "**/*"
  name: 
    - "s3-to-s3-latest-build.zip" 
version: 0.1

