"""empty message

Revision ID: 441727d718ce
Revises: 
Create Date: 2020-11-05 17:36:28.455928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '441727d718ce'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_input')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"flasklogin-users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flasklogin-users_pkey'),
    sa.UniqueConstraint('email', name='flasklogin-users_email_key')
    )
    op.create_table('user_input',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('osoite', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kunta', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('postinumero', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('asuntotyyppi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('asuinala', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rakennusvuosi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('huone_lkm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kerros', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kerros_yht', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kunto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tontti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vastike', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('vuokrattu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hissi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sauna', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parveke', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tonttiala', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('muu_kerrosala', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('hinta', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_input_pkey')
    )
    # ### end Alembic commands ###
